#!/usr/bin/env python3
"""Regenerate crates/gamedata/assets/world-nodes.json from the vendored
community node dataset (crates/gamedata/assets/vendor/nodes_vanilla.json,
MIT — github.com/Hirashi3630/satisfactory_node_heatmap, extracted in-game via
FicsIt-Networking; counts cross-confirmed against satisfactory-calculator.com's
1.1 mapData). Coordinates: UE cm → meters (/100), +Y = south, Z = up.

Included: solid resource nodes + crude-oil nodes (node_type == "Node").
Excluded (BACKLOG): fracking-well satellites, geysers — the extractor model
doesn't cover them yet. Cave/entrance zoning isn't in the dataset; the schema
keeps supporting it (see worldnodes.rs unit tests)."""
import json, os, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = json.load(open(f"{root}/crates/gamedata/assets/vendor/nodes_vanilla.json"))

REGIONS = [
    {"id": "grass-fields", "name": "GRASS FIELDS", "labelX": -700, "labelY": 2000},
    {"id": "rocky-desert", "name": "ROCKY DESERT", "labelX": -2200, "labelY": 400},
    {"id": "northern-forest", "name": "NORTHERN FOREST", "labelX": 900, "labelY": -1100},
    {"id": "dune-desert", "name": "DUNE DESERT", "labelX": 3000, "labelY": -2200},
]

def region_of(x, y):
    best, bd = None, None
    for r in REGIONS:
        d = (x - r["labelX"]) ** 2 + (y - r["labelY"]) ** 2
        if bd is None or d < bd:
            best, bd = r["id"], d
    return best

nodes = []
for n in src:
    if n.get("node_type") != "Node":
        continue
    x = round(n["location"]["x"] / 100.0, 1)
    y = round(n["location"]["y"] / 100.0, 1)
    z = round(n["location"]["z"] / 100.0, 1)
    nodes.append({
        "id": n["id"].lower(),
        "item": n["class_name"],
        "purity": n["purity"].lower(),
        "x": x, "y": y, "z": z,
        "region": region_of(x, y),
    })
nodes.sort(key=lambda n: (n["item"], n["id"]))
xs = [n["x"] for n in nodes]; ys = [n["y"] for n in nodes]

out = {
    "version": 2,
    "source": "Generated by scripts/gen-world-nodes.py from the vendored community dataset (MIT, github.com/Hirashi3630/satisfactory_node_heatmap; cross-confirmed vs satisfactory-calculator.com 1.1 mapData). Game content © Coffee Stain Studios. See NOTICE.",
    "bounds": {"minX": -3247.0, "minY": -3750.0, "maxX": 4253.1, "maxY": 3750.0},
    "regions": REGIONS,
    "nodes": nodes,
}
dst = f"{root}/crates/gamedata/assets/world-nodes.json"
json.dump(out, open(dst, "w"), indent=1)
print(f"{len(nodes)} nodes -> {dst}; x [{min(xs)},{max(xs)}] y [{min(ys)},{max(ys)}]")
from collections import Counter
print(Counter(n['item'] for n in nodes))
